## PRODUCTION
spring:
  config:
    activate:
      on-profile: "prod"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

### JPA ###
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

### FLYWAY ###
  flyway:
    url:
    user:
    password:
    baseline-on-migrate: true

### ACTUATOR ###
management:
  endpoints:
    web:
      exposure:
        include: prometheus

## LOGGING
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info
