spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        auto: false
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
